apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: ds_prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: ds_loki
    url: http://loki:3100
    editable: false

  - name: Alertmanager
    type: alertmanager
    uid: ds_alertmanager
    url: http://alertmanager:9093
    editable: false
    jsonData:
      implementation: prometheus
