name: crypto_platform
version: "3.0.0"
config-version: 2

profile: crypto_platform

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  crypto_platform:
    staging:
      +materialized: view
      +schema: silver      # Staging models map directly to the 'silver' database/schema
    marts:
      +materialized: table
      +schema: gold        # Gold models map directly to the 'gold' database/schema
